spring:
  application:
    name: "online-shop"
    minio:
      url: "http://localhost:9000"
      accessKey: sABA0mYsoKCHStwDYRNH
      secretKey: lyAHsn4uTb4xUrlRsLtvIOGuj1LmWTVc3YNDyNKC
      getErrorMessage: "unable to get the resource"
      postErrorMessage: "unable to post the resource"
      bucket: "simple-online-shop"
    redis:
      host: localhost
      port: 6379

  datasource:
    url: "jdbc:postgresql://localhost:5432/online-shop"
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    whitelabel:
      enabled: false